
runtime: php55
api_version: 1
threadsafe: false

handlers:

- url: /
  script: login.php

- url: /register.php
  script: register.php

- url: /home.php
  script: add_stock.php
  
- url: /task_2.php
  script: Task_2.php


